---
# tasks file for base-config. yum clean cannot be used with yum module as per ansible documentation
  - name: Run yum clean
    shell: yum clean all

  - name: Install EPEL repos 
    yum:
      name: http://admin.na.shared.opentlc.com/repos/tower//3.7.0-4/rhel-7-server-extras-rpms
      state: present
