---
# tasks file for base-config. yum clean cannot be used with yum module as per ansible documentation
  - name: Run yum clean
    shell: yum clean all

  - name: Add repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: http://admin.na.shared.opentlc.com/repos/tower//3.7.0-4/rhel-7-server-optional-rpms
